version: '3.6'
services:
  service:
    build:
      context: .
      target: service
      dockerfile: Dockerfile.test
    image: react-ts-sandbox:test
    ports:
      - "8080:8080"
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080
