version: '3.8'

services:
  notes:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: sandbox-frontend
    container_name: sandbox-frontend
    ports:
      - 5173:5173
    stdin_open: true
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379