version: '3.8'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: sandbox-frontend
    container_name: frontend
    ports:
      - 5173:5173
    stdin_open: true
  redis:
    build:
      context: backend/redis
      dockerfile: Dockerfile
    container_name: redis
    ports:
      - 6379:6379
  backend:
    image: backend-image
    container_name: backend
    build:
      context: backend/api_auto_generated
      dockerfile: Dockerfile
      target: service
    ports:
      - "8080:8080"
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080