/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.11
 */
export type User = {
  /**
   * User email
   *
   * @format email
   */
  email: string;
  /**
   * A list of roles assigned to the user
   */
  roles: string[];
};

export type HTTPValidationError = {
  detail?: ValidationError[];
};

export type ValidationError = {
  loc: string[];
  msg: string;
  type: string;
};
